# Strassen's Approach

In [11]:
## Recurence relation = 7T(n/2) + n^2(matrix addition)
## using Master's Theorem Time complexity = O(n^2.81)
## Brute Force approach and divide and conquer both T.C = O(n^3)
## Actual divide and conquer is Recurence relation = 8T(n/2) + n^2
import numpy as np
def split(matrix):
    row, col = matrix.shape
    row2, col2 = row//2, col//2
    return matrix[:row2, :col2], matrix[:row2, col2:], matrix[row2:, :col2], matrix[row2:, col2:]

def strassen(x,y):
    #  Base Case when size of matrices is 1x1
    if len(x) == 1:
        return x*y
    
    #Spliting the matrices into quadrants. This will be done recursively
    #until the base is reached 
    a, b, c, d = split(x)
    e, f, g, h = split(y)
    
    #computing the 7 products, recursively (p1,p2,....p7)
    p1 = strassen(a, f-h)
    p2 = strassen(a+b, h)
    p3 = strassen(c+d, e)
    p4 = strassen(d, g-e)
    p5 = strassen(a+d, e+h)
    p6 = strassen(b-d, g+h)
    p7 = strassen(a-c, e+f)
    
    #Computing the value of the 4 quadrants of the finl matrix c
    c11 = p5 + p4 - p2 + p6
    c12 = p1 + p2
    c21 = p3 + p4
    c22 = p1 + p5 -p3 - p7

    #Combining the 4 quadrants into a single matrix bh stacking horizontally and vertically.
    c = np.vstack((np.hstack((c11, c12)), np.hstack((c21, c22))))
    return c
##Driver code

A = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3], [2,2,2,2]])
B = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3], [2,2,2,2]])
print("Matrix multiplication result:")
print(strassen(A, B))


Matrix multiplication result:
[[ 8  8  8  8]
 [16 16 16 16]
 [24 24 24 24]
 [16 16 16 16]]


# Median of 2 sorted array

In [12]:
#method definition
def medianofSortarray(num1,num2):
    n1 = len(num1)
    n2 = len(num2)
    n3 = n1+n2
    arr = n3*[0]
    new_1 = n1*[0]
    new_2 = n2*[0]
    
    for m in range(n1):
        new_1[m] = num1[m]
    for n in range(n2):
        new_2[n] = num2[n]
        
    p = 0
    q = 0
    k = 0
    
    while p<n1 and q<n2:
        if new_1[p] <= new_2[q]:
            arr[k] = new_1[p]
            p += 1
        else:
            arr[k] = new_2[q]
            q += 1
        k += 1
    while p<n1:
        arr[k] = new_1[p]
        p += 1
        k += 1
    while q<n2:
        arr[k] = new_2[q]
        q += 1
        k += 1
    i = 0
    j = len(arr)-1
    mid = i + (j-i)//2
    if len(arr) % 2 == 0:
        median = (arr[mid] + arr[mid+1])/2
    else:
        median = arr[mid]
    
    return median
        





##Driver Code
num1 = [1,3]
num2 = [2]
result = medianofSortarray(num1,num2)
print(result)


2


In [13]:
class Solution:
    def findMedianSortedArrays(nums1, nums2):
        n1 = len(nums1)
        n2 = len(nums2)
        n3 = n1+n2
        new_num1 = n1*[0]
        new_num2 = n2*[0]
        arr = n3*[0]
        for m in range(n1):
            new_num1[m] = nums1[m]
        for n in range(n2):
            new_num2[n] = nums2[n]
        p = 0
        q = 0
        k = 0
        while p<n1 and q<n2:
            if new_num1[p] <= new_num2[q]:
                arr[k] = new_num1[p]
                p += 1
            else:
                arr[k] = new_num2[q]
                q += 1
            k += 1
        while p<n1:
            arr[k] = new_num1[p]
            p += 1
            k += 1
        while q<n2:
            arr[k] = new_num2[q]
            q += 1
            k += 1
        i = 0
        j = len(arr)-1
        mid = i + (j-i)//2
        median = 0
        if len(arr) % 2 == 0:
            median = (arr[mid]+arr[mid+1])/2
        else:
            median = arr[mid]
        return median 

    
nums1 = [1,3]
nums2 = [2]
s1 = Solution
print(s1.findMedianSortedArrays(nums1, nums2))

2


# Pow(x,n) 

In [16]:
#method definition
#time complxity = O(logn)
def powerofanelement(x,n):
    if n == 0:
        return 1
    elif n == 1:
        return x
    elif n == -1:
        return (1/x)
    else:
        #divide--> O(1)
        mid = n//2
        # conquer-->T(n/2)
        b = powerofanelement(x,mid)
        result = b*b
    if n % 2 == 0:
        return result
    else:
        return result * x
        



##driver Code
x = 5.0
n = -8
result = powerofanelement(x,n)
print(result)

2.560000000000002e-06


# Divide and Two

In [6]:
##Method definition

def divide(dividend, divisor):
        divid = abs(dividend)
        div = abs(divisor)
        result = 0
        while divid >= div:
            shift = 0
            while divid >= (div << shift):
                shift += 1
            result += (1 << shift - 1)
            divid -= div << shift-1
        if (dividend < 0 and divisor >= 0) or (divisor< 0 and dividend >= 0):
            result = -result
        else:
            result = result

        return min(max(result, -2147483648), 2147483647)
    
    
##Driver code
dividend = 47
divisor = 4
result = divide(dividend, divisor)
print(" Divide two number w/o division, multiplication, modulo:", result)

 Divide two number w/o division, multiplication, modulo: 11
